# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20160912_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.get_image_path),
        ),
    ]
