# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20160914_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='img/tovar.jpg', null=True, upload_to=store.models.get_image_path),
        ),
    ]
